name: Generate Streak Stats

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate streak stats
        uses: denvercoder1/github-readme-streak-stats@main
        with:
          options: "user=xGanne&theme=dracula&hide_border=false&locale=pt_BR"
          path: "github-readme-streak-stats.svg"

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add github-readme-streak-stats.svg
          git commit -m "Generated streak stats" || echo "No changes to commit"
          git push
